spring:
  application:
    name: ktca
  profiles:
    include: prod, base, datasource, ktca

server:
  port: 21002
  servlet:
    context-path: /ktc

management:
  server:
    port: 21003
  endpoints:
    web:
      base-path: /ktc/actuator
