spring:
  data:
    redis:
      cluster:
        nodes:
          - 10.30.210.153:7000
          - 10.30.210.153:7001
          - 10.30.210.153:7010
          - 10.30.210.153:7011
          - 10.30.210.153:7020
          - 10.30.210.153:7021
      password: 123456
      timeout: 2000