spring:
  data:
    redis:
      # Sentinel 설정 삭제 예정
      sentinel:
        master: mymaster
        nodes: dev3.konadc.com:26379
      cluster:
        nodes:
          - dev3.konadc.com:7000
          - dev3.konadc.com:7001
          - dev3.konadc.com:7010
          - dev3.konadc.com:7011
          - dev3.konadc.com:7020
          - dev3.konadc.com:7021
      password: 123456
      timeout: 2000