spring:
  application:
    name: ktca
  profiles:
    include: dev, base, datasource

server:
  port: 21002
  servlet:
    context-path: /ktca

management:
  server:
    port: 21003
  endpoints:
    web:
      base-path: /ktca/actuator
