spring:
  application:
    name: ktc
  profiles:
    include: base, ktc
    active: test

server:
  port: 21000
  servlet:
    context-path: /ktc

management:
  server:
    port: 21001
  endpoints:
    web:
      base-path: /ktc/actuator

logging:
  file:
    path: log
    name: ktc-log