spring:
  application:
    name: ktc
  profiles:
    active: test
    include: base, ktc

server:
  port: 21000
  servlet:
    context-path: /ktc

management:
  server:
    port: 21001
  endpoints:
    web:
      base-path: /ktc/actuator
